from __future__ import annotations

import json
from pathlib import Path
from typing import Any

FRONTEND_ROOT = Path(__file__).parent.parent / "pipeline Iran" / "robo-advisor-dashboard"
FRONTEND_DATA_DIR = FRONTEND_ROOT / "public"


def _write_json_atomic(path: Path, data: Any) -> None:
    """
    Perform an atomic write by writing data to a temporary file first,
    then replacing the destination path. This prevents consumers from reading
    partially written or incomplete files.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    tmp_path.replace(path)


def read_json(path: Path) -> Any | None:
    """
    Read a JSON file generated by external pipeline scripts (e.g., backtester.py,
    portfolio_optimizer.py). Returns None if the file does not exist.
    """
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def write_rankings_json(rows: list[dict], data_dir: Path = FRONTEND_DATA_DIR) -> Path:
    """
    Write live stock rankings to JSON.

    rows: List of dictionaries containing keys:
    symbol, alpha_score, predicted_class, price, change_percent,
    drop_prob, neutral_prob, growth_prob (use None for missing values).
    """
    out_path = data_dir / "live_rankings.json"
    _write_json_atomic(out_path, rows)
    print(f"✅ {len(rows)} symbols written to '{out_path}'.")
    return out_path


def write_equity_curve_json(points: list[dict], data_dir: Path = FRONTEND_DATA_DIR) -> Path:
    """
    Write equity curve points to JSON.

    points: List of dictionaries containing date, portfolio_value, and market_value.
    """
    out_path = data_dir / "equity_curve.json"
    _write_json_atomic(out_path, points)
    print(f"✅ {len(points)} equity curve points written to '{out_path}'.")
    return out_path


def write_portfolio_json(
    portfolio_weights: dict,
    metrics: dict,
    data_dir: Path = FRONTEND_DATA_DIR,
) -> Path:
    """
    Write portfolio allocation weights and evaluation metrics to JSON for frontend presentation.

    portfolio_weights: Dict mapping asset symbols/names to weights.
    metrics: Dict with keys total_return, sharpe_ratio, max_drawdown, risk_exposure (as decimals).
    """
    out_path = data_dir / "portfolio.json"
    payload = {"portfolio_weights": portfolio_weights, "metrics": metrics}
    _write_json_atomic(out_path, payload)
    print(f"✅ Portfolio weights and metrics written to '{out_path}'.")
    return out_path


def jalali_int_to_label(jalali_date: int) -> str:
    """
    Convert an integer Jalali date (e.g., 14041021) into a formatted string '1404/10/21'.
    """
    s = str(int(jalali_date))
    return f"{s[:4]}/{s[4:6]}/{s[6:8]}"


def build_equity_curve_from_backtest(xlsx_path: Path) -> list[dict]:
    """
    Read backtest output Excel file and convert it into dashboard-compatible equity curve data points.
    """
    import pandas as pd

    if not xlsx_path.exists():
        raise FileNotFoundError(f"❌ Backtest file not found: {xlsx_path}")

    df = pd.read_excel(xlsx_path)
    points = []
    for _, row in df.iterrows():
        points.append({
            "date": jalali_int_to_label(row["date"]),
            "portfolio_value": round(float(row["total_value"])),
            "market_value": round(float(row["market_value"])),
        })
    return points